### ISSUE TITLE
max height?

### ISSUE THREAD

**Issue by toddaa** [jonmiles/bootstrap-treeview#55]
I didn't see this in the options so I thought I'd throw it out there:

Can a max-height be added so that no matter the number of nodes the box wont grow larger than the max.  Also would need to incorporate a vertical scroll bar.

Any change this can be done with a little CSS code?

**Comment by jonmiles** [comment]
Just add the following css to you project.

e.g

```css
.treeview {
	max-height: 300px;
	overflow-y: scroll;
}
```
